spring.application.name=checkpoint2
server.error.include-stacktrace=never
server.error.include-message=always
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/checkpoint2
